//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkDbFirst.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHONE
    {
        public int ID { get; set; }
        public string PHONENAME { get; set; }
    
        public virtual SIMCARD SIMCARD { get; set; }
    }
}
